package fr.erias.iamsystem_java.matcher;

import java.util.List;

import fr.erias.iamsystem_java.tokenize.IToken;
import fr.erias.iamsystem_java.tokenize.ITokenizer;

public class Span<T extends IToken> implements ISpan<T>
{

	private final List<T> tokens;

	/**
	 * Create a Span instance.
	 *
	 * @param tokens Tokens generated by a {@link ITokenizer}
	 */
	public Span(List<T> tokens)
	{
		this.tokens = tokens;
	}

	@Override
	public int end_i()
	{
		return tokens.get(tokens.size() - 1).i();
	}

	@Override
	public int start_i()
	{
		return tokens.get(0).i();
	}

	@Override
	public List<T> tokens()
	{
		return tokens;
	}
}
