package fr.erias.iamsystem_java.annotation;

import java.util.Collection;
import java.util.List;

import fr.erias.iamsystem_java.brat.IBratFormatterF;
import fr.erias.iamsystem_java.keywords.IKeyword;
import fr.erias.iamsystem_java.tokenize.IToken;
import fr.erias.iamsystem_java.tokenize.ITokenizer;
import fr.erias.iamsystem_java.tree.INode;

/**
 * Matcher output
 *
 * @author Sebastien Cossin
 */
public class Annotation extends Span implements IAnnotation
{

	public static IPrintAnnot printAnnot = new PrintAnnot();

	public static void setBratFormatter(IBratFormatterF bratFormatter)
	{
		Annotation.printAnnot = new PrintAnnot(bratFormatter);
	}

	public static void setPrintAnnot(IPrintAnnot printAnnot)
	{
		Annotation.printAnnot = printAnnot;
	}

	private final List<Collection<String>> algos;
	private final INode lastState;
	private final List<IToken> stopTokens;
	private String text;

	/**
	 * Create an annotation
	 *
	 * @param tokens     a sequence of generic tokens generated by a
	 *                   {@link ITokenizer}
	 * @param algos      for each token, the list of algorithms that matched.
	 * @param lastState  a final state of iamsystem algorithm containing the keyword
	 *                   that matched this sequence of tokens.
	 * @param stopTokens the list of stopwords tokens of the document.
	 */
	public Annotation(List<IToken> tokens, List<Collection<String>> algos, INode lastState, List<IToken> stopTokens)
	{
		super(tokens);
		this.algos = algos;
		this.lastState = lastState;
		this.stopTokens = stopTokens;
	}

	@Override
	public int compareTo(IAnnotation o)
	{
		int diffStart = this.start() - o.start();
		if (diffStart != 0)
		{
			return diffStart;
		} else
		{
			return this.end() - o.end();
		}
	}

	@Override
	public List<Collection<String>> getAlgos()
	{
		return algos;
	}

	@Override
	public Collection<IKeyword> getKeywords()
	{
		return lastState.getKeywords();
	}

	@Override
	public String getText()
	{
		return text;
	}

	@Override
	public INode lastState()
	{
		return this.lastState;
	}

	/**
	 * Return the annotation text (if set).
	 *
	 * @param text
	 */
	@Override
	public void setText(String text)
	{
		this.text = text;
	}

	@Override
	public List<IToken> stopTokens()
	{
		return stopTokens;
	}

	@Override
	public String toString()
	{
		return Annotation.printAnnot.toString(this);
	}
}
